[[group]]
template = "https://*.kaspa.stream"
nodes = ["eric", "troy", "sean", "maxim"]

# [[group]]
# template = "https://*.kaspa.red"
# nodes = ["cole", "ivan", "oscar", "zane"]

# [[group]]
# template = "https://*.kaspa.green"
# nodes = ["gary", "hugo", "finn", "evan"]

# [[group]]
# template = "https://*.kaspa.blue"
# nodes = ["neil", "dave", "kyle", "toby"]

# [[group]]
# template = "https://*.kaspacalc.net"
# nodes = ["rudy", "todd", "clay", "walt"]

# [[group]]
# enable = true
# template = "https://*.kaspa-ng.org"
# nodes = ["john", "mike", "paul", "alex"]

# [[group]]
# enable = true
# template = "https://*.kaspa-ng.io"
# nodes = ["jake", "mark", "adam", "liam"]

# [[group]]
# enable = true
# template = "https://*.kaspa-ng.net"
# nodes = ["noah", "ryan", "jack", "luke"]

# --

# [[group]]
# template = "https://*.kaspa.stream"
# nodes = ["brad", "dean", "fred", "joel"]

# [[resolver]]
# enable = false
# address = "http://127.0.0.1:8888"
