[[resolver]]
url = "https://*.kaspa-ng.org"
enable = true

[[resolver]]
url = "https://*.kaspa-ng.io"
enable = true

[[resolver]]
url = "https://*.kaspa-ng.net"
enable = true

[[resolver]]
url = "http://127.0.0.1:8888"
enable = false
