# [[group]]
# enable = true
# template = "https://*.kaspa-ng.org"
# nodes = ["jack", "john", "paul", "luke"]

# [[group]]
# enable = true
# template = "https://*.kaspa-ng.io"
# nodes = ["mark", "noah", "liam", "ryan"]

# [[group]]
# enable = true
# template = "https://*.kaspa-ng.net"
# nodes = ["max", "evan", "alex", "eric"]

[[group]]
enable = true
template = "https://*.kaspa.stream"
nodes = ["adam", "owen", "sean", "kyle"]

# [[group]]
# enable = false
# template = "https://*."
# nodes = ["jake", "jace", "cody", "troy"]

[[resolver]]
enable = false
address = "http://127.0.0.1:8888"
